sudo: required
services:
  - docker

before_install:
  - docker build -t maxoptland/docker-react -f Dockerfile.dev .

script:
  - docker run maxoptland/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-{id}"
  bucket_path: "docker-react"
  on:
    branch: master
